# Generated by Django 4.0.5 on 2022-06-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_alter_contato_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='sobrenomenome',
            new_name='sobrenome',
        ),
    ]
