# Generated by Django 4.1.4 on 2022-12-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
    ]
